#include "vda5050_210/msg/header.idl"
#include "vda5050_210/msg/batteryState.idl"
#include "vda5050_210/msg/error.idl"

module vda5050_210
{
  module msg
  {
    struct AGVPosition
    {
      double x;
      double y;
      double theta;
      string map_id;
    };

    struct Velocity
    {
      double vx;
      double vy;
      double omega;
    };

    struct State
    {
      Header header;

      string order_id;
      uint32 order_update_id;

      string last_node_id;
      string last_edge_id;

      AGVPosition agv_position;
      Velocity velocity;

      BatteryState battery_state;
      sequence<Error> errors;

      bool driving;
      bool paused;
      bool emergency_stop;
    };
  };
};
