controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
      ros__parameters:
        use_stamped_vel: false
        left_wheel_names: ["joint_wheel_frontleft"]
        right_wheel_names: ["joint_wheel_frontright"]
        wheel_separation: 0.4   # à adapter à ton URDF
        wheel_radius: 0.1       # idem
        cmd_vel_timeout: 0.5
        publish_rate: 50
